// src/app/core/header/header.component.ts
import { ChangeDetectionStrategy, Component, inject } from '@angular/core';

import { SettingsService } from '../../shared/services/settings.service';

@Component({
  selector: 'app-header',
  standalone: false,
  templateUrl: './header.component.html',
  styleUrls: ['./header.component.scss'],
  changeDetection: ChangeDetectionStrategy.OnPush
})
export class HeaderComponent {
  private _settingsService = inject(SettingsService);
  readonly settings = this._settingsService.settings;

  toggleSettings() {
    this._settingsService.toggleSettings();
  }

  scrollTop() {
    window.scrollTo(0, 0);
  }
}

<header>
    <div id="header">
      <a class="home-link" routerLink="/news/1" routerLinkActive="active" (click)="scrollTop()">
        <div class="logo-inner"></div>
        <img class="logo" src="assets/images/logo.svg" alt="Logo">
      </a>
      <div class="header-text">
        <div class="left">
          <span class="header-nav">
            <a routerLink="/newest/1" routerLinkActive="active" (click)="scrollTop()">new</a>
              |
            <a routerLink="/show/1" routerLinkActive="active" (click)="scrollTop()">show</a>
              |
            <a routerLink="/ask/1" routerLinkActive="active" (click)="scrollTop()">ask</a>
              |
            <a routerLink="/jobs/1" routerLinkActive="active" (click)="scrollTop()">jobs</a>
          </span>
        </div>
      </div>
      <div class="info">
        <img class="settings" src="assets/images/cog.svg" alt="Settings" (click)="toggleSettings()">
      </div>
    </div>
    <app-settings *ngIf="settings().showSettings"></app-settings>
  </header>

// src/core/Header.tsx
import { NavLink } from 'react-router';

import { useSettings } from '../settings/SettingsContext';
import { Settings } from './Settings';
import './Header.scss';

const NAV_LINKS = [
    { to: '/newest/1', label: 'new' },
    { to: '/show/1', label: 'show' },
    { to: '/ask/1', label: 'ask' },
    { to: '/jobs/1', label: 'jobs' },
];

function scrollTop() {
    window.scrollTo(0, 0);
}

export function Header() {
    const { settings, toggleSettings } = useSettings();

    return (
        <header>
            <div id="header">
                <NavLink className="home-link" to="/news/1" onClick={scrollTop}>
                    <div className="logo-inner"></div>
                    <img className="logo" src="/assets/images/logo.svg" alt="Logo" />
                </NavLink>
                <div className="header-text">
                    <div className="left">
                        <span className="header-nav">
                            {NAV_LINKS.map((link, i) => (
                                <span key={link.to}>
                                    {i > 0 && ' | '}
                                    <NavLink to={link.to} onClick={scrollTop}>
                                        {link.label}
                                    </NavLink>
                                </span>
                            ))}
                        </span>
                    </div>
                </div>
                <div className="info">
                    <img className="settings" src="/assets/images/cog.svg" alt="Settings" onClick={toggleSettings} />
                </div>
            </div>
            {settings.showSettings && <Settings />}
        </header>
    );
}
