// src/item-details/ItemDetails.tsx
import { useEffect } from 'react';
import { Link, useNavigate, useParams } from 'react-router';
import clsx from 'clsx';

import { useItem } from '../api/queries';
import { ErrorMessage } from '../shared/components/ErrorMessage';
import { Loader } from '../shared/components/Loader';
import { formatCommentCount, hasExternalUrl } from '../shared/utils/format';
import { sanitizeHtml } from '../shared/utils/sanitize';
import { useSettings } from '../settings/SettingsContext';
import { Comment } from './Comment';
import './ItemDetails.scss';

export default function ItemDetails() {
    const { id } = useParams<{ id: string }>();
    const itemId = Number(id);
    const { data: item, isError } = useItem(itemId);
    const { settings } = useSettings();
    const navigate = useNavigate();

    useEffect(() => {
        window.scrollTo(0, 0);
    }, [itemId]);

    const linkTarget = settings.openLinkInNewTab ? '_blank' : undefined;
    const linkRel = settings.openLinkInNewTab ? 'noopener' : undefined;

    return (
        <div className="main-content item-page">
            {!item && !isError && <Loader />}
            {!item && isError && <ErrorMessage message="Could not load item comments." />}

            {item && (
                <div className="item">
                    <div className="mobile item-header">
                        <p className="title-block">
                            <span className="back-button" onClick={() => navigate(-1)}></span>
                            {hasExternalUrl(item.url) ? (
                                <a className="title" href={item.url} target={linkTarget} rel={linkRel}>
                                    {item.title}
                                </a>
                            ) : (
                                <Link className="title" to={`/item/${item.id}`}>
                                    {item.title}
                                </Link>
                            )}
                        </p>
                    </div>
                    <div
                        className={clsx('laptop', {
                            'item-header': item.comments_count > 0 || item.type === 'job',
                            'head-margin': item.text,
                        })}
                    >
                        {hasExternalUrl(item.url) ? (
                            <p>
                                <a className="title" href={item.url} target={linkTarget} rel={linkRel}>
                                    {item.title}
                                </a>
                                {item.domain && (
                                    <>
                                        {' '}
                                        <span className="domain">({item.domain})</span>
                                    </>
                                )}
                            </p>
                        ) : (
                            <p>
                                <Link className="title" to={`/item/${item.id}`}>
                                    {item.title}
                                </Link>
                            </p>
                        )}
                        <div className="subtext">
                            {item.type !== 'job' && (
                                <span>
                                    {item.points} points by <Link to={`/user/${item.user}`}>{item.user}</Link>
                                </span>
                            )}
                            <span className={clsx({ 'item-details': item.type !== 'job' })}>
                                {item.time_ago}
                                {item.type !== 'job' && (
                                    <span>
                                        {' | '}
                                        <Link to={`/item/${item.id}`}>{formatCommentCount(item.comments_count)}</Link>
                                    </span>
                                )}
                            </span>
                        </div>
                    </div>
                    {item.type === 'poll' && (
                        <div className="pollResults">
                            {item.poll?.map((pollResult, i) => (
                                <div key={i} className="pollContent">
                                    <div dangerouslySetInnerHTML={sanitizeHtml(pollResult.content)}></div>
                                    <div className="subtext">{pollResult.points} points</div>
                                    <div
                                        className="pollBar"
                                        style={{
                                            width: `${(pollResult.points / (item.poll_votes_count || 1)) * 100}%`,
                                        }}
                                    ></div>
                                </div>
                            ))}
                        </div>
                    )}
                    <p className="subject" dangerouslySetInnerHTML={sanitizeHtml(item.content)}></p>
                    <ul className="comment-list">
                        {item.comments?.map((comment) => (
                            <li key={comment.id}>
                                <Comment comment={comment} />
                            </li>
                        ))}
                    </ul>
                </div>
            )}
        </div>
    );
}

// src/app/item-details/item-details.component.ts
import { Component, OnInit } from '@angular/core';
import { ActivatedRoute } from '@angular/router';
import { Location } from '@angular/common';
import { Subscription } from 'rxjs';

import { HackerNewsAPIService } from '../shared/services/hackernews-api.service';
import { SettingsService } from '../shared/services/settings.service';

import { Story } from '../shared/models/story';
import { Settings } from '../shared/models/settings';

@Component({
  selector: 'app-item-details',
  standalone: false,
  templateUrl: './item-details.component.html',
  styleUrls: ['./item-details.component.scss']
})
export class ItemDetailsComponent implements OnInit {
  sub: Subscription;
  item: Story;
  errorMessage = '';
  settings: Settings;

  constructor(
    private _hackerNewsAPIService: HackerNewsAPIService,
    private _settingsService: SettingsService,
    private route: ActivatedRoute,
    private _location: Location
  ) {
    this.settings = this._settingsService.settings;
  }

  ngOnInit() {
    this.sub = this.route.params.subscribe(params => {
      let itemID = +params['id'];
      this._hackerNewsAPIService.fetchItemContent(itemID).subscribe(item => {
        this.item = item;
      }, error => this.errorMessage = 'Could not load item comments.');
    });
    window.scrollTo(0, 0);
  }

  goBack() {
    this._location.back();
  }

  get hasUrl(): boolean {
    return this.item.url.indexOf('http') === 0;
  }

}

<div class="main-content">
  <app-loader *ngIf="!item && !errorMessage"></app-loader>
  <app-error-message [message]="errorMessage" *ngIf="!item && errorMessage !== ''"></app-error-message>

  <div *ngIf="item" class="item">
    <div class="mobile item-header">
      <p class="title-block">
        <span class="back-button" (click)="goBack()"></span>
        <a *ngIf="hasUrl" class="title" href="{{item.url}}" [attr.target]="settings().openLinkInNewTab ? '_blank' : null" [attr.rel]="settings().openLinkInNewTab ? 'noopener' : null">
          {{item.title}}
        </a>
        <a *ngIf="!hasUrl" class="title" [routerLink]="['/item', item.id]"
          routerLinkActive="active">
          {{item.title}}
        </a>
      </p>
    </div>
    <div class="laptop" [class.item-header]="item.comments_count > 0 || item.type === 'job'" [class.head-margin]="item.text">
      <p *ngIf="hasUrl">
        <a class="title" href="{{item.url}}" [attr.target]="settings().openLinkInNewTab ? '_blank' : null" [attr.rel]="settings().openLinkInNewTab ? 'noopener' : null">
        {{item.title}}
        </a>
        <span *ngIf="item.domain" class="domain">({{item.domain}})</span>
      </p>
      <p *ngIf="!hasUrl">
        <a class="title" [routerLink]="['/item', item.id]" routerLinkActive="active">
        {{item.title}}
        </a>
      </p>
      <div class="subtext">
        <span *ngIf="item.type !== 'job'">
        {{item.points}} points by
          <a [routerLink]="['/user', item.user]" routerLinkActive="active">{{item.user}}</a>
        </span>
        <span [class.item-details]="item.type !== 'job'">
          {{item.time_ago}}
          <span *ngIf="item.type !== 'job'"> |
            <a [routerLink]="['/item', item.id]" routerLinkActive="active">
             {{item.comments_count | comment }}
            </a>
          </span>
        </span>
      </div>
    </div>
    <div *ngIf="item.type === 'poll'" class="pollResults">
      <div *ngFor="let pollResult of item.poll" class="pollContent">
        <div [innerHTML]="pollResult.content"></div>
        <div class="subtext">{{pollResult.points}} points</div>
        <div class="pollBar" [ngStyle]="{'width': pollResult.points/item.poll_votes_count*100+'%'}"></div>
      </div>
    </div>
    <p class="subject" [innerHTML]="item.content"></p>
    <ul class="comment-list">
      <li *ngFor="let comment of item.comments; trackBy: trackById" >
        <app-comment [comment]="comment"></app-comment>
      </li>
    </ul>
  </div>
</div>
