// src/core/Settings.tsx
import type { Theme } from '../shared/models/settings';
import { useSettings } from '../settings/SettingsContext';
import './Settings.scss';

const THEMES: { value: Theme; label: string }[] = [
    { value: 'default', label: 'Default' },
    { value: 'night', label: 'Night' },
    { value: 'amoledblack', label: 'Black (AMOLED)' },
];

export function Settings() {
    const { settings, toggleSettings, toggleOpenLinksInNewTab, setTheme, setFont, setSpacing } = useSettings();

    return (
        <div id="popup1" className="overlay">
            <div className="popup">
                <h1>Settings</h1>
                <hr />
                <span className="close" onClick={toggleSettings}>
                    &times;
                </span>
                <div className="content">
                    <div className="control-section">
                        <h2>Links</h2>
                        <label>
                            <input
                                type="checkbox"
                                checked={settings.openLinkInNewTab}
                                onChange={toggleOpenLinksInNewTab}
                            />{' '}
                            Open links in a new tab
                        </label>
                    </div>
                    <div className="theme-controls">
                        <div className="control-section">
                            <h2>Select a theme</h2>
                            {THEMES.map((theme) => (
                                <div key={theme.value}>
                                    <label>
                                        <input
                                            name="theme"
                                            type="radio"
                                            value={theme.value}
                                            checked={settings.theme === theme.value}
                                            onChange={() => setTheme(theme.value)}
                                        />{' '}
                                        {theme.label}
                                    </label>
                                </div>
                            ))}
                        </div>
                        <div className="control-section">
                            <h2>Change Font</h2>
                            <div>
                                <label>
                                    Font size:
                                    <input
                                        min="1"
                                        name="titleFontSize"
                                        type="number"
                                        value={settings.titleFontSize}
                                        onChange={(e) => setFont(e.target.value)}
                                    />
                                </label>
                            </div>
                            <div>
                                <label>
                                    List spacing:
                                    <input
                                        min="0"
                                        name="listSpacing"
                                        type="number"
                                        value={settings.listSpacing}
                                        onChange={(e) => setSpacing(e.target.value)}
                                    />
                                </label>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    );
}

// src/app/core/settings/settings.component.ts
import { ChangeDetectionStrategy, Component, inject } from '@angular/core';

import { SettingsService } from '../../shared/services/settings.service';

@Component({
  selector: 'app-settings',
  standalone: false,
  templateUrl: './settings.component.html',
  styleUrls: ['./settings.component.scss'],
  changeDetection: ChangeDetectionStrategy.OnPush
})
export class SettingsComponent {
  private _settingsService = inject(SettingsService);
  readonly settings = this._settingsService.settings;

  closeSettings() {
    this._settingsService.toggleSettings();
  }

  toggleOpenLinksInNewTab() {
    this._settingsService.toggleOpenLinksInNewTab();
  }

  selectTheme(theme) {
    this._settingsService.setTheme(theme);
  }

  changeTitleFont(val){
    this._settingsService.setFont(val);
  }

  changeSpacing(val){
    this._settingsService.setSpacing(val);
  }
}

<div id="popup1" class="overlay">
    <div class="popup">
        <h1>Settings</h1>
        <hr>
        <span class="close" (click)="closeSettings()">&times;</span>
        <div class="content">
            <div class="control-section">
                <h2>Links</h2>
                <input 
                    type="checkbox" 
                    [checked]="settings().openLinkInNewTab" 
                    (change)="toggleOpenLinksInNewTab()" />
                    Open links in a new tab
            </div>
            <div class="theme-controls">
                <div class="control-section">
                    <h2>Select a theme</h2>
                    <div>
                        <label>
                        <input #default 
                            name="theme" 
                            type="radio" 
                            value="default" 
                            [checked]="settings().theme === default.value"
                            (click)="selectTheme(default.value)" />
                            Default
                        </label>
                    </div>
                    <div>
                        <label>
                        <input #night 
                            name="theme" 
                            type="radio" 
                            value="night" 
                            [checked]="settings().theme === night.value" 
                            (click)="selectTheme(night.value)" />
                            Night
                        </label>
                    </div>
                    <div>
                        <label>
                        <input 
                            #amoledblack 
                            name="theme" 
                            type="radio" 
                            value="amoledblack" 
                            [checked]="settings().theme === amoledblack.value"
                            (click)="selectTheme(amoledblack.value)" />
                            Black (AMOLED)
                        </label>
                    </div>
                </div>
                <div class="control-section">
                    <h2>Change Font</h2>
                    <div>
                        <label>
                        Font size:
                        <input 
                            #titleFont 
                            min="1" 
                            [value]="settings().titleFontSize" 
                            name="theme" 
                            type="number" 
                            (keyup)="changeTitleFont(titleFont.value)" />
                        </label>
                    </div>
                    <div>
                        <label>
                        List spacing:
                        <input 
                            #listSpacing 
                            min="0" 
                            [value]="settings().listSpacing" 
                            name="theme" 
                            type="number" 
                            (keyup)="changeSpacing(listSpacing.value)" />
                        </label>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
